feat: adding cpf as a mandatory field
startteamm/servidor-inspira pull request #26
Opened 2024-12-01 22:55 UTC by rafabpg

## Motivação

Como teremos alteração para o cpf ser obrigatório no cadastro, houve  a necessidade dessa alteração no backend

## Proposta de solução

Troquei na validação o cpf não pode ser enviado como nulo

## Links Importante

- Trello: [Tornar campo CPF obrigatório na criação do usuário](https://trello.com/c/zib67FNW/84-tornar-campo-cpf-obrigat%C3%B3rio-na-cria%C3%A7%C3%A3o-do-usu%C3%A1rio)

2024-12-01 22:56 UTC, rafabpg commented
![](https://github.trello.services/images/mini-trello-icon.png) [Tornar campo CPF obrigatório na criação do usuário](https://trello.com/c/zib67FNW/84-tornar-campo-cpf-obrigat%C3%B3rio-na-cria%C3%A7%C3%A3o-do-usu%C3%A1rio)

2024-12-04 01:59 UTC, riquedss requested changes

2024-12-04 01:59 UTC, riquedss commented on app/models/user.rb
> +  validates :cpf, format: { with: REGEX_CPF }, allow_blank: false
Na linha 33, é a verdadeira validação de presença. Ela só estava sendo executada quando o cara ia para o pagamento e precisava completar cadastro. Seguindo a regra de **can_validate_account_update_params**.

Agora que será obrigatório na criação do usuário, aconselho tirar o cpf da linha 33 e adicionar na 23 porque a linha 27 é responsável em validar o formato.

2024-12-09 02:59 UTC, riquedss approved these changes

2024-12-10 16:38 UTC, merged