Feature/activate admin activities and activities category
startteamm/servidor-inspira pull request #27
Opened 2024-12-23 21:45 UTC by rafabpg

## Motivação

Mudança necessária para facilitar na criação de categorias de atividades e as atividades

## Proposta de solução

Criar no active admin

## Testes
![atividade](https://github.com/user-attachments/assets/8973b6b5-1688-48c4-80e4-93fd7d636820)
![categ](https://github.com/user-attachments/assets/62808515-2ccf-4ccd-a7f6-49b73ab263a4)

## Links Importante

- Trello: [Crud de atividades e atividade categoria](https://trello.com/c/MoDwJqnM/87-crud-de-atividades-e-atividade-categoria?filter=label:Back-End)

2024-12-23 23:08 UTC, riquedss commented on app/admin/activity_categories.rb
> +    column "Título", :title
Se for só para traduzir o campo acho que a boa é utilizar locales, o que acha?

2024-12-23 23:12 UTC, riquedss requested changes

2024-12-23 23:12 UTC, riquedss commented on app/admin/activity_categories.rb
> +      f.input :title, label: "Título"
Uma vez criado a locale desse recurso para seus campos irá refletir em todas as partes.

2024-12-23 23:19 UTC, rafabpg commented on app/admin/activity_categories.rb
> +    column "Título", :title
po pode ser depois da pra fazer isso então,

2024-12-23 23:20 UTC, rafabpg commented
Atualizei

2025-01-08 00:21 UTC, riquedss approved these changes

2025-01-20 18:44 UTC, merged